# docker-compose.yml
services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 ros_chat.asgi:application
    volumes:
      - .:/app
      - static:/app/static
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: dan
      POSTGRES_PASSWORD: 1453
    expose:
      - "5432"

  redis:
    image: redis:7.4.1-alpine3.20
    expose:
      - "6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static:/static
      - media:/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:

